openapi: 3.0.1
info:
  title: GenderAPI
  description: API Definition of GenderAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/gender
paths:
  /:
    get:
      responses:
        default:
          description: Default response
