openapi: 3.0.1
info:
  title: Station2API
  description: API Definition of Station2API
  version: 1.0.0
servers:
- url: http://localhost:8290/station2
paths:
  /:
    get:
      responses:
        default:
          description: Default response
