openapi: 3.0.1
info:
  title: Station1API
  description: API Definition of Station1API
  version: 1.0.0
servers:
- url: http://localhost:8290/station1
paths:
  /:
    get:
      responses:
        default:
          description: Default response
