openapi: 3.0.1
info:
  title: Station3API
  description: API Definition of Station3API
  version: 1.0.0
servers:
- url: http://localhost:8290/station3
paths:
  /:
    get:
      responses:
        default:
          description: Default response
