openapi: 3.0.1
info:
  title: StationAPI
  description: API Definition of StationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/station
paths:
  /:
    get:
      responses:
        default:
          description: Default response
