openapi: 3.0.1
info:
  title: EcommerceAPI
  description: API Definition of EcommerceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/orders
paths:
  /:
    get:
      responses:
        default:
          description: Default response
