openapi: 3.0.1
info:
  title: GreetingsAPI
  description: API Definition of GreetingsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/greetings
paths:
  /{name}:
    get:
      parameters:
      - name: name
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
